### ISSUE TITLE
sqlite3.IntegrityError

### ISSUE THREAD

**Issue by abhi-r3v0** [alterakey/trueseeing#127]
Hi!
I'm getting this error while trying to analyze an APK file (without report.html)

## Command used
`trueseeing app.apk`

## Error
```
analyze: removing leftover
analyzed: 2417430 ops, 82990 methods, 15952 classes                    
analyzed: finalizing
Traceback (most recent call last):
  File "/usr/local/bin/trueseeing", line 10, in <module>
    sys.exit(shell())
  File "/usr/local/lib/python3.7/site-packages/trueseeing/shell.py", line 200, in shell
    if processed(f, [v for k,v in signatures.items() if k in signature_selected], output_format=output_format):
  File "/usr/local/lib/python3.7/site-packages/trueseeing/shell.py", line 48, in processed
    context.analyze(apkfilename)
  File "/usr/local/lib/python3.7/site-packages/trueseeing/context.py", line 75, in analyze
    trueseeing.code.parse.SmaliAnalyzer(self.store()).analyze(open(fn, 'r', encoding='utf-8') for fn in self.disassembled_classes())
  File "/usr/local/lib/python3.7/site-packages/trueseeing/code/parse.py", line 90, in analyze
    self.store.op_finalize()
  File "/usr/local/lib/python3.7/site-packages/trueseeing/store.py", line 51, in op_finalize
    trueseeing.literalquery.Store(self.db).stage2()
  File "/usr/local/lib/python3.7/site-packages/trueseeing/literalquery.py", line 35, in stage2
    self.c.executescript(f.read())
sqlite3.IntegrityError: UNIQUE constraint failed: class_class_name.class_name
```

**Comment by alterakey** [comment]
Thank you for your report, @abhi-r3v0 !
We're sorry for the delay.

It looks like, .. the apk has been obfuscated with some advanced obfuscator (i.e. other than ProGuard)?

We are eager to look into this issue. Can you send us the apk?
Thanks for your patience!

**Comment by alterakey** [comment]
One case seems to go like this:
```
sqlite> select op as class, coalesce(v9,v8,v7,v6,v5,v4,v3,v2,v1,v) as class_name from op_vecs where t='directive' and v='class' limit 8;
1|;
67|;
95|;
590|;
694|;
765|;
1363|;
3058|;
```

**Comment by alterakey** [comment]
The issue should now be fixed. Please test the next release and please re-open if it persists.
@abhi-r3v0, thanks again for your report, and sorry for being late.
