### ISSUE TITLE
Cannot build code base when cache volume is not used

### ISSUE THREAD

**Issue by alterakey** [alterakey/trueseeing#254]
- [ ] justify
- [ ] fix
- [ ] deploy

```
$ docker run -it --rm -v $(pwd)/../t:/out trueseeing --inspect <reducted>
[+] Trueseeing 2.1.8 [inspect mode]
ts[<reducted>]> a
[*] analyzing <reducted>
[*] analyze: disassembling... done.
[*] analyze: 7609909 ops, 64568 classes, 366265 methods.
[*] analyze: finalizing
[-] fatal: unhandled exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/trueseeing/app/inspect.py", line 209, in run
	await ent(tokens)
  File "/usr/local/lib/python3.11/site-packages/trueseeing/app/inspect.py", line 289, in _analyze
	await context.analyze()
  File "/usr/local/lib/python3.11/site-packages/trueseeing/core/context.py", line 85, in analyze
	SmaliAnalyzer(self.store()).analyze()
  File "/usr/local/lib/python3.11/site-packages/trueseeing/core/code/parse.py", line 98, in analyze
	self._store.op_finalize()
  File "/usr/local/lib/python3.11/site-packages/trueseeing/core/store.py", line 66, in op_finalize
	StorePrep(self.db).stage2()
  File "/usr/local/lib/python3.11/site-packages/trueseeing/core/literalquery.py", line 45, in stage2
	self.c.executescript(f.read())
sqlite3.DatabaseError: database disk image is malformed

ts[<reducted>]> !
/out # df
Filesystem           1K-blocks      Used Available Use% Mounted on
overlay               61610796  18007016  40441720  31% /
tmpfs                    65536         0     65536   0% /dev
tmpfs                  2007484         0   2007484   0% /sys/fs/cgroup
shm                      65536         0     65536   0% /dev/shm
mount0               482797652 462919076  19878576  96% /out
/dev/disk/by-label/data-volume
					  61610796  18007016  40441720  31% /etc/resolv.conf
/dev/disk/by-label/data-volume
					  61610796  18007016  40441720  31% /etc/hostname
/dev/disk/by-label/data-volume
					  61610796  18007016  40441720  31% /etc/hosts
tmpfs                  2007484         0   2007484   0% /proc/acpi
tmpfs                    65536         0     65536   0% /proc/keys
tmpfs                    65536         0     65536   0% /proc/timer_list
tmpfs                  2007484         0   2007484   0% /proc/scsi
tmpfs                  2007484         0   2007484   0% /sys/firmware
/out # ls /cache/
f23dbd23c206a0455259827e6e1bdd8d89886fd862b64fdd619282bcab655694
/out # ls -l /cache/f23dbd23c206a0455259827e6e1bdd8d89886fd862b64fdd619282bcab655694/
total 3817620
-rw-r--r--    1 root     root     3656208384 Oct 26 13:16 store.db
-rw-r--r--    1 root     root         16928 Oct 26 13:15 store.db-journal
-rw-r--r--    1 root     root     254672447 Oct 26 13:10 target.apk
```

**Comment by alterakey** [comment]
Closing with invalid; re-open when things change.
Workaround is seemingly: use qemu, or mount some volume to /cache.
... current use of vz triggering some bug?

Quick test on: macOS 14.1, colima 0.5.6, lima 0.18.0

vz/virtiofs: FAIL
vz/sshfs: FAIL
qemu/sshfs: OK
