### ISSUE TITLE
sqlite3.IntegrityError: UNIQUE constraint failed: ops_method.op

### ISSUE THREAD

**Issue by Drjacky** [alterakey/trueseeing#308]
```bash
Status: Downloaded newer image for alterakey/trueseeing:latest
analyze: disassembling... done.
analyze: 4232021 ops, 71223 classes, methods...                    Traceback (most recent call last):
  File "/usr/local/bin/trueseeing", line 8, in <module>
    sys.exit(invoke())
             ^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/trueseeing/app/_dummy.py", line 31, in invoke
    trueseeing.app.shell.Shell().invoke()
  File "/usr/local/lib/python3.11/site-packages/trueseeing/app/shell.py", line 255, in invoke
    return self._launch(ScanMode(files).invoke(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/trueseeing/app/shell.py", line 148, in _launch
    return asyncio.run(coro)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/trueseeing/app/scan.py", line 53, in invoke
    if await session.invoke(f):
       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/trueseeing/app/scan.py", line 82, in invoke
    await context.analyze()
  File "/usr/local/lib/python3.11/site-packages/trueseeing/core/context.py", line 85, in analyze
    SmaliAnalyzer(self.store()).analyze()
  File "/usr/local/lib/python3.11/site-packages/trueseeing/core/code/parse.py", line 94, in analyze
    analyzed_methods = self._store.op_generate_methodmap(c=c)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/trueseeing/core/store.py", line 93, in op_generate_methodmap
    c.execute('insert into ops_method(method,op) select tmp1.op,ops.op from tmp1 join tmp2 on (tmp1.rowid=tmp2.rowid) left join ops on (ops.op between tmp1.op and tmp2.op)')
sqlite3.IntegrityError: UNIQUE constraint failed: ops_method.op
```

**Comment by alterakey** [comment]
Hello @Drjacky , thank you for your report.
We think this is a duplicate case of #290 , so please try scanning again with the current image (alterakey/trueseeing:latest).
Thank you.

**Comment by alterakey** [comment]
@Drjacky: thank you for taking time to confirm the fix!
